stages:
  - build
  - deploy

# DEV ENV
dev-build:
  tags:
    - trigger-dev
  stage: build
  script:
    - trigger -h "http://gitlab.dsc.com" -a "${CI_BOT_ACCESS_TOKEN}" -u "/api/v4/projects" -p "${TRIGGER_TOKEN}" -o 1 -b dev -i 419 -e STAGE=build -e DOCKER_TAG=${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA}
  only:
    - dev

dev-deploy:
  tags:
    - trigger-dev
  stage: deploy
  script:
    - trigger -h "http://gitlab.dsc.com" -a "${CI_BOT_ACCESS_TOKEN}" -u "/api/v4/projects" -p "${TRIGGER_TOKEN}" -o 0 -b dev -i 419 -e STAGE=deploy -e DOCKER_TAG=${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA}
  only:
    - dev
  when: on_success

